require 'bundler'
Bundler::GemHelper.install_tasks

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new

task default: [:spec]

# On Rails 8 the dummy app generated by Solidus::InstallGenerator lacks
# app/assets/config/manifest.js, and sprockets-rails 3.5 aborts boot with
# Sprockets::Railtie::ManifestNeededError before any db task runs. Seed the manifest right
# after the app is generated and before the db is set up, then run db setup as separate
# bin/rails invocations so a chained db:create/db:migrate can't leave an empty sqlite file
# (mirrors solidusio/solidus#6327, solidusio/solidus#3379).
desc 'Generates a dummy app for testing'
task :test_app do
  ENV['LIB_NAME'] = 'solidus_flexi_variants'
  ENV['RAILS_ENV'] = 'test'

  require 'generators/solidus/install/install_generator' unless defined?(Solidus::InstallGenerator)
  require 'generators/spree/dummy/dummy_generator'
  require ENV['LIB_NAME']

  dummy_path = File.expand_path('spec/dummy', __dir__)

  Spree::DummyGenerator.start ["--lib_name=#{ENV['LIB_NAME']}", "--quiet"]

  # Seed the manifest before InstallGenerator, which shells out to
  # `rake railties:install:migrations` — that child process boots the dummy app, and on Rails 8
  # sprockets-rails 3.5 aborts with Sprockets::Railtie::ManifestNeededError when the manifest is
  # absent, so the core migrations would never be copied (mirrors solidusio/solidus#6327, #3379).
  manifest = File.join(dummy_path, 'app/assets/config/manifest.js')
  unless File.exist?(manifest)
    require 'fileutils'
    FileUtils.mkdir_p(File.dirname(manifest))
    File.write(manifest, "//= link_tree ../images\n//= link_directory ../stylesheets .css\n")
  end

  Solidus::InstallGenerator.start ["--lib_name=#{ENV['LIB_NAME']}", "--auto-accept", "--with-authentication=false", "--payment-method=none", "--migrate=false", "--seed=false", "--sample=false", "--quiet", "--user_class=Spree::User"]

  puts 'Setting up dummy database...'
  Dir.chdir(dummy_path) do
    sh 'bin/rails db:environment:set RAILS_ENV=test'
    sh 'bin/rails db:drop db:create RAILS_ENV=test'
    sh 'bin/rails db:migrate VERBOSE=false RAILS_ENV=test'
  end

  begin
    require "generators/#{ENV['LIB_NAME']}/install/install_generator"
    puts 'Running extension installation generator...'
    "#{ENV['LIB_NAME'].camelize}::Generators::InstallGenerator".constantize.start(['--auto-run-migrations'])
  rescue LoadError
    # No extension generator to run
  end
end
